stages:
  - build
  - test
  - create_image
  - deploy

variables:
  MVN_IMAGE: maven:3.9.9-amazoncorretto-21-al2023
  SECURE_FILES_DOWNLOAD_PATH: "./"
  DB_PRIVATE_IP: " "

build:
  stage: build
  image: $MVN_IMAGE
  script:
    - cd SkyShop
    - echo "aws.accessKeyId=$AWS_ACCESS_KEY_ID" >> src/main/resources/application-secrets.properties
    - echo "aws.secretAccessKey=$AWS_SECRET_ACCESS_KEY" >> src/main/resources/application-secrets.properties
    - echo "sendgrid.key = $SENDGRID_API_KEY" >> src/main/resources/application-secrets.properties
    - echo "$JUANKEYS" > juankeys.pem
    - chmod 600 juankeys.pem
    - echo "Maven getting db ip"
    - dnf install -y aws-cli bind-utils
    - dnf install mysql
    - DB_PRIVATE_IP=$(nslookup mydb.c5wcu4a6u8bc.us-east-1.rds.amazonaws.com | grep Address | tail -n 1 | awk '{print $2}')
    - echo "spring.datasource.url=jdbc:mysql://$DB_PRIVATE_IP:3306/mydb" >> src/main/resources/application-secrets.properties
    - ssh -i juankeys.pem -L 3306:$DB_PRIVATE_IP:3306 ec2-user@54.162.85.173 -N &
    - mysql -h 127.0.0.1 -P 3306 -u admin -p
    - echo "Maven compile started"
    - mvn compile
    - rm src/main/resources/application-secrets.properties
  only:
    - main

test:
  stage: test
  image: $MVN_IMAGE
  script:
    - cd SkyShop
    - echo "aws.accessKeyId=$AWS_ACCESS_KEY_ID" > src/main/resources/application-secrets.properties
    - echo "aws.secretAccessKey=$AWS_SECRET_ACCESS_KEY" >> src/main/resources/application-secrets.properties
    - echo "sendgrid.key = $SENDGRID_API_KEY" >> src/main/resources/application-secrets.properties
    - echo "$JUANKEYS" > juankeys.pem
    - chmod 600 juankeys.pem
    - echo "Maven getting db ip"
    - dnf install -y aws-cli bind-utils
    - dnf install mysql
    - DB_PRIVATE_IP=$(nslookup mydb.c5wcu4a6u8bc.us-east-1.rds.amazonaws.com | grep Address | tail -n 1 | awk '{print $2}')
    - echo "spring.datasource.url=jdbc:mysql://$DB_PRIVATE_IP:3306/mydb" >> src/main/resources/application-secrets.properties
    - ssh -i juankeys.pem -L 3306:$DB_PRIVATE_IP:3306 ec2-user@54.162.85.173 -N &
    - mysql -h 127.0.0.1 -P 3306 -u admin -p
    - echo "Testeando código de nuevo"
    - mvn test
    - rm src/main/resources/application-secrets.properties
  only:
    - main

create_image:
  stage: create_image
  image: docker:stable
  services:
    - docker:dind
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd SkyShop
    - echo "aws.accessKeyId=$AWS_ACCESS_KEY_ID" > src/main/resources/application-secrets.properties
    - echo "aws.secretAccessKey=$AWS_SECRET_ACCESS_KEY" >> src/main/resources/application-secrets.properties
    - echo "sendgrid.key = $SENDGRID_API_KEY" >> src/main/resources/application-secrets.properties
    - echo "$JUANKEYS" > juankeys.pem
    - chmod 600 juankeys.pem
    - echo "Maven getting db ip"
    - dnf install -y aws-cli bind-utils
    - dnf install mysql
    - DB_PRIVATE_IP=$(nslookup mydb.c5wcu4a6u8bc.us-east-1.rds.amazonaws.com | grep Address | tail -n 1 | awk '{print $2}')
    - echo "spring.datasource.url=jdbc:mysql://$DB_PRIVATE_IP:3306/mydb" >> src/main/resources/application-secrets.properties
    - ssh -i juankeys.pem -L 3306:$DB_PRIVATE_IP:3306 ec2-user@54.162.85.173 -N &
    - mysql -h 127.0.0.1 -P 3306 -u admin -p
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t juancruzmarzetti/sky-shop:back .
    - docker push juancruzmarzetti/sky-shop:back
    - rm juankeys.pem
    - rm src/main/resources/application-secrets.properties
  only:
    - main

deploy:
  stage: deploy
  image: python:3.9
  before_script:
    - cd SkyShop
    - echo "aws.accessKeyId=$AWS_ACCESS_KEY_ID" > src/main/resources/application-secrets.properties
    - echo "aws.secretAccessKey=$AWS_SECRET_ACCESS_KEY" >> src/main/resources/application-secrets.properties
    - echo "sendgrid.key = $SENDGRID_API_KEY" >> src/main/resources/application-secrets.properties
    - echo "$JUANKEYS" > juankeys.pem
    - chmod 600 juankeys.pem
    - pip install ansible
    - mkdir ~/.ssh
    - touch ~/.ssh/config
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | sh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - echo "Maven getting db ip"
    - dnf install -y aws-cli bind-utils
    - dnf install mysql
    - DB_PRIVATE_IP=$(nslookup mydb.c5wcu4a6u8bc.us-east-1.rds.amazonaws.com | grep Address | tail -n 1 | awk '{print $2}')
    - echo "spring.datasource.url=jdbc:mysql://$DB_PRIVATE_IP:3306/mydb" >> src/main/resources/application-secrets.properties
    - ssh -i juankeys.pem -L 3306:$DB_PRIVATE_IP:3306 ec2-user@54.162.85.173 -N &
    - mysql -h 127.0.0.1 -P 3306 -u admin -p
    - rm src/main/resources/application-secrets.properties
  script:
    - ansible-playbook -i hosts.ini playbook.yaml --key-file "juankeys.pem"
    - rm juankeys.pem
  only:
    - main
